# Generated by Django 4.0.4 on 2022-05-26 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnombre', models.CharField(max_length=50)),
                ('appaterno', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('telefono', models.IntegerField(unique=True)),
                ('mensaje', models.TextField()),
                ('archivo', models.FileField(null=True, upload_to='fotos')),
            ],
        ),
        migrations.CreateModel(
            name='Periodista',
            fields=[
                ('id_periodista', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField(unique=True)),
                ('imagen', models.ImageField(null=True, upload_to='fotos')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webcaosnews.area')),
            ],
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('portada', models.ImageField(null=True, upload_to='fotos')),
                ('contenido', models.CharField(max_length=1500)),
                ('etiquetas', models.CharField(max_length=150)),
                ('fecha', models.DateField(auto_now=True)),
                ('ubicacion', models.CharField(max_length=50)),
                ('aprobada', models.BooleanField(default=False)),
                ('comentario', models.TextField(default='--')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webcaosnews.categoria')),
                ('id_periodista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webcaosnews.periodista')),
            ],
        ),
    ]
