# Generated by Django 4.0.4 on 2022-05-24 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webcaosnews', '0002_periodista_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='area',
            old_name='id',
            new_name='id_area',
        ),
        migrations.RemoveField(
            model_name='periodista',
            name='id',
        ),
        migrations.AddField(
            model_name='periodista',
            name='id_periodista',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('portada', models.ImageField(null=True, upload_to='fotos')),
                ('contenido', models.CharField(max_length=1500)),
                ('etiquetas', models.CharField(max_length=150)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webcaosnews.categoria')),
            ],
        ),
    ]
