# Generated by Django 4.0.4 on 2022-05-27 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcaosnews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticias',
            name='id_periodista',
        ),
    ]
