# Generated by Django 4.0.4 on 2022-05-27 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcaosnews', '0003_region'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Region',
            new_name='Regiones',
        ),
    ]
