# Generated by Django 4.0.4 on 2022-05-27 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webcaosnews', '0004_rename_region_regiones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webcaosnews.regiones'),
        ),
    ]
