# Generated by Django 4.0.4 on 2022-05-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcaosnews', '0005_alter_noticias_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='contenido',
            field=models.TextField(),
        ),
    ]
