# Generated by Django 4.0.4 on 2022-05-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcaosnews', '0006_alter_noticias_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='archivo',
            field=models.FileField(null=True, upload_to='fotos/contacto'),
        ),
    ]
