# Generated by Django 4.0.4 on 2022-05-28 23:10

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('webcaosnews', '0009_alter_contacto_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='CL'),
        ),
    ]
