# Generated by Django 4.0.4 on 2022-05-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcaosnews', '0011_alter_contacto_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='archivo',
            field=models.FileField(null=True, upload_to='archivos_contacto'),
        ),
    ]
