# Generated by Django 4.0.4 on 2022-05-29 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcaosnews', '0012_alter_contacto_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodista',
            name='imagen',
            field=models.ImageField(default='fotos/default_photo.png', null=True, upload_to='fotos'),
        ),
    ]
