# Generated by Django 4.0.4 on 2022-05-29 01:48

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('webcaosnews', '0013_alter_periodista_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodista',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='CL', unique=True),
        ),
    ]
