# Generated by Django 4.0.4 on 2022-05-31 22:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webcaosnews', '0014_alter_periodista_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='usuario',
            field=models.CharField(default='--', max_length=60),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='archivo',
            field=models.FileField(default='fotos/defecto.png', upload_to='archivos_contacto'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='fecha',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha'),
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('auto_inc', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='galeria')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webcaosnews.noticias')),
            ],
        ),
    ]
