# Generated by Django 4.0.4 on 2022-05-31 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcaosnews', '0015_noticias_usuario_alter_contacto_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='archivo',
            field=models.ImageField(default='fotos/defecto.png', upload_to='archivos_contacto/%Y/%m/%d/'),
        ),
    ]
