# Generated by Django 4.0.4 on 2022-05-31 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcaosnews', '0016_alter_contacto_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='portada',
            field=models.ImageField(default='fotos/defecto.png', upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
